image: alpine:latest
# Global Variables default for every job - (Can be overwritten in individual job definitions)
variables:
  KUBERNETES_VERSION: 1.15.0
  HELM_VERSION: 2.13.1
  DOCKER_DRIVER: overlay2
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
# Outline of stages and their sequence
stages:
#  - pre-build
  - build
  - verify
#  - tag-release
  - deploy
#  - test
#  - tag-latest
#  - cleanup
# Job definitions
include:
  # Pre-Build Jobs
  #- local: 'cicd/check-semver/check-semver.yml'
  # Build stage jobs (No requirement for already built image)
  - local: 'cicd/build-image/build-image.yml'
  #- local: 'cicd/sast-nodejsscan/sast-nodejsscan.yml'
  #- local: 'cicd/sast-retirejs/sast-retirejs.yml'
  #- local: 'cicd/sast-secrets/sast-secrets.yml'
  #- local: 'cicd/software-composition/sca.yml'
  # Review stage jobs (Require image)
  #- local: 'cicd/code-quality/code-quality.yml'
  - local: 'cicd/deploy/deploy-branch.yml'
  #- local: 'cicd/image-scan/image-scan.yml'
  #- local: 'cicd/unit-test/unit-tests.yml'
  # Deploy (non-feature/bug branches) stage jobs (Waiting for tests to pass before deploy)
  - local: 'cicd/deploy/deploy-staging.yml'
  - local: 'cicd/deploy/deploy-prod.yml'
  # DAST & Peformance stage Jobs (Require running environment)
  #- local: 'cicd/browser-test/browser-testing.yml'
  #- local: 'cicd/dast/dast.yml'
  #- local: 'cicd/load-test/load-test.yml'
  #- local: 'cicd/stress-test/stress-test.yml'
  # Tag latest stage jobs
  #- local: 'cicd/tag-latest/tag-latest.yml'
  # Cleanup stage Jobs
  #- local: 'cicd/cleanup/delete-feature-environment.yml'
  #- local: 'cicd/cleanup/delete-staging-environment.yml'
